---
- hosts: host-1
  become: yes
  tasks:
  - name: make sure docker is installed.
    apt:
      name: docker.io
      state: latest

  - name: add user to docker group.
    shell: usermod -aG docker devops

  - name: start docker service.
    systemd:
      name: docker
      state: started
      enabled: true