---
- hosts: host-1
  become: yes
  tasks:
  - name: make sure docker is installed.
    apt:
      name: docker.io
      state: latest
    command:
      cmd: usermod -aG docker devops
    service:
      name: docker.io
      state: Started